title: Bacox
description: > # this means to ignore newlines until "baseurl:"
  Bacox.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Bart Cox # add your name
author-img: bacox.jpg # add your photo
about-author: Master student Computer Science at the TU Delft. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: bacox # add your Github handle
social-linkedin: bart-cox # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: #mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]